/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.aqitrade.raduga.messagebus.messages;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class InstrumentMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"InstrumentMessage\",\"namespace\":\"com.aqitrade.raduga.messagebus.messages\",\"fields\":[{\"name\":\"exchangeID\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"exchangeName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"instrumentID\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"instrumentName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"instrumentDesignator\",\"type\":{\"type\":\"enum\",\"name\":\"InstrumentDesignator\",\"symbols\":[\"cash_instrument\",\"future_instrument\",\"stock_instrument\"]}},{\"name\":\"longMarginRate\",\"type\":\"double\"},{\"name\":\"shortMarginRate\",\"type\":\"double\"},{\"name\":\"openComissionRate\",\"type\":\"double\"},{\"name\":\"closeComissionRate\",\"type\":\"double\"},{\"name\":\"price\",\"type\":\"double\"},{\"name\":\"openPrice\",\"type\":\"double\"},{\"name\":\"closePrice\",\"type\":\"double\"},{\"name\":\"highPrice\",\"type\":\"double\"},{\"name\":\"lowPrice\",\"type\":\"double\"},{\"name\":\"highLimit\",\"type\":\"double\"},{\"name\":\"lowLimit\",\"type\":\"double\"},{\"name\":\"volume\",\"type\":\"long\"},{\"name\":\"settlementPrice\",\"type\":\"double\"},{\"name\":\"bid\",\"type\":\"double\"},{\"name\":\"ask\",\"type\":\"double\"},{\"name\":\"unitSize\",\"type\":\"int\"},{\"name\":\"createDate\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public String exchangeID;
  @Deprecated public String exchangeName;
  @Deprecated public String instrumentID;
  @Deprecated public String instrumentName;
  @Deprecated public InstrumentDesignator instrumentDesignator;
  @Deprecated public double longMarginRate;
  @Deprecated public double shortMarginRate;
  @Deprecated public double openComissionRate;
  @Deprecated public double closeComissionRate;
  @Deprecated public double price;
  @Deprecated public double openPrice;
  @Deprecated public double closePrice;
  @Deprecated public double highPrice;
  @Deprecated public double lowPrice;
  @Deprecated public double highLimit;
  @Deprecated public double lowLimit;
  @Deprecated public long volume;
  @Deprecated public double settlementPrice;
  @Deprecated public double bid;
  @Deprecated public double ask;
  @Deprecated public int unitSize;
  @Deprecated public String createDate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}.
   */
  public InstrumentMessage() {}

  /**
   * All-args constructor.
   */
  public InstrumentMessage(String exchangeID, String exchangeName, String instrumentID, String instrumentName, InstrumentDesignator instrumentDesignator, Double longMarginRate, Double shortMarginRate, Double openComissionRate, Double closeComissionRate, Double price, Double openPrice, Double closePrice, Double highPrice, Double lowPrice, Double highLimit, Double lowLimit, Long volume, Double settlementPrice, Double bid, Double ask, Integer unitSize, String createDate) {
    this.exchangeID = exchangeID;
    this.exchangeName = exchangeName;
    this.instrumentID = instrumentID;
    this.instrumentName = instrumentName;
    this.instrumentDesignator = instrumentDesignator;
    this.longMarginRate = longMarginRate;
    this.shortMarginRate = shortMarginRate;
    this.openComissionRate = openComissionRate;
    this.closeComissionRate = closeComissionRate;
    this.price = price;
    this.openPrice = openPrice;
    this.closePrice = closePrice;
    this.highPrice = highPrice;
    this.lowPrice = lowPrice;
    this.highLimit = highLimit;
    this.lowLimit = lowLimit;
    this.volume = volume;
    this.settlementPrice = settlementPrice;
    this.bid = bid;
    this.ask = ask;
    this.unitSize = unitSize;
    this.createDate = createDate;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return exchangeID;
    case 1: return exchangeName;
    case 2: return instrumentID;
    case 3: return instrumentName;
    case 4: return instrumentDesignator;
    case 5: return longMarginRate;
    case 6: return shortMarginRate;
    case 7: return openComissionRate;
    case 8: return closeComissionRate;
    case 9: return price;
    case 10: return openPrice;
    case 11: return closePrice;
    case 12: return highPrice;
    case 13: return lowPrice;
    case 14: return highLimit;
    case 15: return lowLimit;
    case 16: return volume;
    case 17: return settlementPrice;
    case 18: return bid;
    case 19: return ask;
    case 20: return unitSize;
    case 21: return createDate;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: exchangeID = (String)value$; break;
    case 1: exchangeName = (String)value$; break;
    case 2: instrumentID = (String)value$; break;
    case 3: instrumentName = (String)value$; break;
    case 4: instrumentDesignator = (InstrumentDesignator)value$; break;
    case 5: longMarginRate = (Double)value$; break;
    case 6: shortMarginRate = (Double)value$; break;
    case 7: openComissionRate = (Double)value$; break;
    case 8: closeComissionRate = (Double)value$; break;
    case 9: price = (Double)value$; break;
    case 10: openPrice = (Double)value$; break;
    case 11: closePrice = (Double)value$; break;
    case 12: highPrice = (Double)value$; break;
    case 13: lowPrice = (Double)value$; break;
    case 14: highLimit = (Double)value$; break;
    case 15: lowLimit = (Double)value$; break;
    case 16: volume = (Long)value$; break;
    case 17: settlementPrice = (Double)value$; break;
    case 18: bid = (Double)value$; break;
    case 19: ask = (Double)value$; break;
    case 20: unitSize = (Integer)value$; break;
    case 21: createDate = (String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'exchangeID' field.
   */
  public String getExchangeID() {
    return exchangeID;
  }

  /**
   * Sets the value of the 'exchangeID' field.
   * @param value the value to set.
   */
  public void setExchangeID(String value) {
    this.exchangeID = value;
  }

  /**
   * Gets the value of the 'exchangeName' field.
   */
  public String getExchangeName() {
    return exchangeName;
  }

  /**
   * Sets the value of the 'exchangeName' field.
   * @param value the value to set.
   */
  public void setExchangeName(String value) {
    this.exchangeName = value;
  }

  /**
   * Gets the value of the 'instrumentID' field.
   */
  public String getInstrumentID() {
    return instrumentID;
  }

  /**
   * Sets the value of the 'instrumentID' field.
   * @param value the value to set.
   */
  public void setInstrumentID(String value) {
    this.instrumentID = value;
  }

  /**
   * Gets the value of the 'instrumentName' field.
   */
  public String getInstrumentName() {
    return instrumentName;
  }

  /**
   * Sets the value of the 'instrumentName' field.
   * @param value the value to set.
   */
  public void setInstrumentName(String value) {
    this.instrumentName = value;
  }

  /**
   * Gets the value of the 'instrumentDesignator' field.
   */
  public InstrumentDesignator getInstrumentDesignator() {
    return instrumentDesignator;
  }

  /**
   * Sets the value of the 'instrumentDesignator' field.
   * @param value the value to set.
   */
  public void setInstrumentDesignator(InstrumentDesignator value) {
    this.instrumentDesignator = value;
  }

  /**
   * Gets the value of the 'longMarginRate' field.
   */
  public Double getLongMarginRate() {
    return longMarginRate;
  }

  /**
   * Sets the value of the 'longMarginRate' field.
   * @param value the value to set.
   */
  public void setLongMarginRate(Double value) {
    this.longMarginRate = value;
  }

  /**
   * Gets the value of the 'shortMarginRate' field.
   */
  public Double getShortMarginRate() {
    return shortMarginRate;
  }

  /**
   * Sets the value of the 'shortMarginRate' field.
   * @param value the value to set.
   */
  public void setShortMarginRate(Double value) {
    this.shortMarginRate = value;
  }

  /**
   * Gets the value of the 'openComissionRate' field.
   */
  public Double getOpenComissionRate() {
    return openComissionRate;
  }

  /**
   * Sets the value of the 'openComissionRate' field.
   * @param value the value to set.
   */
  public void setOpenComissionRate(Double value) {
    this.openComissionRate = value;
  }

  /**
   * Gets the value of the 'closeComissionRate' field.
   */
  public Double getCloseComissionRate() {
    return closeComissionRate;
  }

  /**
   * Sets the value of the 'closeComissionRate' field.
   * @param value the value to set.
   */
  public void setCloseComissionRate(Double value) {
    this.closeComissionRate = value;
  }

  /**
   * Gets the value of the 'price' field.
   */
  public Double getPrice() {
    return price;
  }

  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(Double value) {
    this.price = value;
  }

  /**
   * Gets the value of the 'openPrice' field.
   */
  public Double getOpenPrice() {
    return openPrice;
  }

  /**
   * Sets the value of the 'openPrice' field.
   * @param value the value to set.
   */
  public void setOpenPrice(Double value) {
    this.openPrice = value;
  }

  /**
   * Gets the value of the 'closePrice' field.
   */
  public Double getClosePrice() {
    return closePrice;
  }

  /**
   * Sets the value of the 'closePrice' field.
   * @param value the value to set.
   */
  public void setClosePrice(Double value) {
    this.closePrice = value;
  }

  /**
   * Gets the value of the 'highPrice' field.
   */
  public Double getHighPrice() {
    return highPrice;
  }

  /**
   * Sets the value of the 'highPrice' field.
   * @param value the value to set.
   */
  public void setHighPrice(Double value) {
    this.highPrice = value;
  }

  /**
   * Gets the value of the 'lowPrice' field.
   */
  public Double getLowPrice() {
    return lowPrice;
  }

  /**
   * Sets the value of the 'lowPrice' field.
   * @param value the value to set.
   */
  public void setLowPrice(Double value) {
    this.lowPrice = value;
  }

  /**
   * Gets the value of the 'highLimit' field.
   */
  public Double getHighLimit() {
    return highLimit;
  }

  /**
   * Sets the value of the 'highLimit' field.
   * @param value the value to set.
   */
  public void setHighLimit(Double value) {
    this.highLimit = value;
  }

  /**
   * Gets the value of the 'lowLimit' field.
   */
  public Double getLowLimit() {
    return lowLimit;
  }

  /**
   * Sets the value of the 'lowLimit' field.
   * @param value the value to set.
   */
  public void setLowLimit(Double value) {
    this.lowLimit = value;
  }

  /**
   * Gets the value of the 'volume' field.
   */
  public Long getVolume() {
    return volume;
  }

  /**
   * Sets the value of the 'volume' field.
   * @param value the value to set.
   */
  public void setVolume(Long value) {
    this.volume = value;
  }

  /**
   * Gets the value of the 'settlementPrice' field.
   */
  public Double getSettlementPrice() {
    return settlementPrice;
  }

  /**
   * Sets the value of the 'settlementPrice' field.
   * @param value the value to set.
   */
  public void setSettlementPrice(Double value) {
    this.settlementPrice = value;
  }

  /**
   * Gets the value of the 'bid' field.
   */
  public Double getBid() {
    return bid;
  }

  /**
   * Sets the value of the 'bid' field.
   * @param value the value to set.
   */
  public void setBid(Double value) {
    this.bid = value;
  }

  /**
   * Gets the value of the 'ask' field.
   */
  public Double getAsk() {
    return ask;
  }

  /**
   * Sets the value of the 'ask' field.
   * @param value the value to set.
   */
  public void setAsk(Double value) {
    this.ask = value;
  }

  /**
   * Gets the value of the 'unitSize' field.
   */
  public Integer getUnitSize() {
    return unitSize;
  }

  /**
   * Sets the value of the 'unitSize' field.
   * @param value the value to set.
   */
  public void setUnitSize(Integer value) {
    this.unitSize = value;
  }

  /**
   * Gets the value of the 'createDate' field.
   */
  public String getCreateDate() {
    return createDate;
  }

  /**
   * Sets the value of the 'createDate' field.
   * @param value the value to set.
   */
  public void setCreateDate(String value) {
    this.createDate = value;
  }

  /** Creates a new InstrumentMessage RecordBuilder */
  public static Builder newBuilder() {
    return new Builder();
  }

  /** Creates a new InstrumentMessage RecordBuilder by copying an existing Builder */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }

  /** Creates a new InstrumentMessage RecordBuilder by copying an existing InstrumentMessage instance */
  public static Builder newBuilder(InstrumentMessage other) {
    return new Builder(other);
  }

  /**
   * RecordBuilder for InstrumentMessage instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<InstrumentMessage>
    implements org.apache.avro.data.RecordBuilder<InstrumentMessage> {

    private String exchangeID;
    private String exchangeName;
    private String instrumentID;
    private String instrumentName;
    private InstrumentDesignator instrumentDesignator;
    private double longMarginRate;
    private double shortMarginRate;
    private double openComissionRate;
    private double closeComissionRate;
    private double price;
    private double openPrice;
    private double closePrice;
    private double highPrice;
    private double lowPrice;
    private double highLimit;
    private double lowLimit;
    private long volume;
    private double settlementPrice;
    private double bid;
    private double ask;
    private int unitSize;
    private String createDate;

    /** Creates a new Builder */
    private Builder() {
      super(InstrumentMessage.SCHEMA$);
    }

    /** Creates a Builder by copying an existing Builder */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.exchangeID)) {
        this.exchangeID = data().deepCopy(fields()[0].schema(), other.exchangeID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.exchangeName)) {
        this.exchangeName = data().deepCopy(fields()[1].schema(), other.exchangeName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.instrumentID)) {
        this.instrumentID = data().deepCopy(fields()[2].schema(), other.instrumentID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.instrumentName)) {
        this.instrumentName = data().deepCopy(fields()[3].schema(), other.instrumentName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.instrumentDesignator)) {
        this.instrumentDesignator = data().deepCopy(fields()[4].schema(), other.instrumentDesignator);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.longMarginRate)) {
        this.longMarginRate = data().deepCopy(fields()[5].schema(), other.longMarginRate);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.shortMarginRate)) {
        this.shortMarginRate = data().deepCopy(fields()[6].schema(), other.shortMarginRate);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.openComissionRate)) {
        this.openComissionRate = data().deepCopy(fields()[7].schema(), other.openComissionRate);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.closeComissionRate)) {
        this.closeComissionRate = data().deepCopy(fields()[8].schema(), other.closeComissionRate);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.price)) {
        this.price = data().deepCopy(fields()[9].schema(), other.price);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.openPrice)) {
        this.openPrice = data().deepCopy(fields()[10].schema(), other.openPrice);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.closePrice)) {
        this.closePrice = data().deepCopy(fields()[11].schema(), other.closePrice);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.highPrice)) {
        this.highPrice = data().deepCopy(fields()[12].schema(), other.highPrice);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.lowPrice)) {
        this.lowPrice = data().deepCopy(fields()[13].schema(), other.lowPrice);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.highLimit)) {
        this.highLimit = data().deepCopy(fields()[14].schema(), other.highLimit);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.lowLimit)) {
        this.lowLimit = data().deepCopy(fields()[15].schema(), other.lowLimit);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.volume)) {
        this.volume = data().deepCopy(fields()[16].schema(), other.volume);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.settlementPrice)) {
        this.settlementPrice = data().deepCopy(fields()[17].schema(), other.settlementPrice);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.bid)) {
        this.bid = data().deepCopy(fields()[18].schema(), other.bid);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.ask)) {
        this.ask = data().deepCopy(fields()[19].schema(), other.ask);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.unitSize)) {
        this.unitSize = data().deepCopy(fields()[20].schema(), other.unitSize);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.createDate)) {
        this.createDate = data().deepCopy(fields()[21].schema(), other.createDate);
        fieldSetFlags()[21] = true;
      }
    }

    /** Creates a Builder by copying an existing InstrumentMessage instance */
    private Builder(InstrumentMessage other) {
            super(InstrumentMessage.SCHEMA$);
      if (isValidValue(fields()[0], other.exchangeID)) {
        this.exchangeID = data().deepCopy(fields()[0].schema(), other.exchangeID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.exchangeName)) {
        this.exchangeName = data().deepCopy(fields()[1].schema(), other.exchangeName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.instrumentID)) {
        this.instrumentID = data().deepCopy(fields()[2].schema(), other.instrumentID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.instrumentName)) {
        this.instrumentName = data().deepCopy(fields()[3].schema(), other.instrumentName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.instrumentDesignator)) {
        this.instrumentDesignator = data().deepCopy(fields()[4].schema(), other.instrumentDesignator);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.longMarginRate)) {
        this.longMarginRate = data().deepCopy(fields()[5].schema(), other.longMarginRate);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.shortMarginRate)) {
        this.shortMarginRate = data().deepCopy(fields()[6].schema(), other.shortMarginRate);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.openComissionRate)) {
        this.openComissionRate = data().deepCopy(fields()[7].schema(), other.openComissionRate);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.closeComissionRate)) {
        this.closeComissionRate = data().deepCopy(fields()[8].schema(), other.closeComissionRate);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.price)) {
        this.price = data().deepCopy(fields()[9].schema(), other.price);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.openPrice)) {
        this.openPrice = data().deepCopy(fields()[10].schema(), other.openPrice);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.closePrice)) {
        this.closePrice = data().deepCopy(fields()[11].schema(), other.closePrice);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.highPrice)) {
        this.highPrice = data().deepCopy(fields()[12].schema(), other.highPrice);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.lowPrice)) {
        this.lowPrice = data().deepCopy(fields()[13].schema(), other.lowPrice);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.highLimit)) {
        this.highLimit = data().deepCopy(fields()[14].schema(), other.highLimit);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.lowLimit)) {
        this.lowLimit = data().deepCopy(fields()[15].schema(), other.lowLimit);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.volume)) {
        this.volume = data().deepCopy(fields()[16].schema(), other.volume);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.settlementPrice)) {
        this.settlementPrice = data().deepCopy(fields()[17].schema(), other.settlementPrice);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.bid)) {
        this.bid = data().deepCopy(fields()[18].schema(), other.bid);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.ask)) {
        this.ask = data().deepCopy(fields()[19].schema(), other.ask);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.unitSize)) {
        this.unitSize = data().deepCopy(fields()[20].schema(), other.unitSize);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.createDate)) {
        this.createDate = data().deepCopy(fields()[21].schema(), other.createDate);
        fieldSetFlags()[21] = true;
      }
    }

    /** Gets the value of the 'exchangeID' field */
    public String getExchangeID() {
      return exchangeID;
    }

    /** Sets the value of the 'exchangeID' field */
    public Builder setExchangeID(String value) {
      validate(fields()[0], value);
      this.exchangeID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /** Checks whether the 'exchangeID' field has been set */
    public boolean hasExchangeID() {
      return fieldSetFlags()[0];
    }

    /** Clears the value of the 'exchangeID' field */
    public Builder clearExchangeID() {
      exchangeID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'exchangeName' field */
    public String getExchangeName() {
      return exchangeName;
    }

    /** Sets the value of the 'exchangeName' field */
    public Builder setExchangeName(String value) {
      validate(fields()[1], value);
      this.exchangeName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /** Checks whether the 'exchangeName' field has been set */
    public boolean hasExchangeName() {
      return fieldSetFlags()[1];
    }

    /** Clears the value of the 'exchangeName' field */
    public Builder clearExchangeName() {
      exchangeName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'instrumentID' field */
    public String getInstrumentID() {
      return instrumentID;
    }

    /** Sets the value of the 'instrumentID' field */
    public Builder setInstrumentID(String value) {
      validate(fields()[2], value);
      this.instrumentID = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /** Checks whether the 'instrumentID' field has been set */
    public boolean hasInstrumentID() {
      return fieldSetFlags()[2];
    }

    /** Clears the value of the 'instrumentID' field */
    public Builder clearInstrumentID() {
      instrumentID = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'instrumentName' field */
    public String getInstrumentName() {
      return instrumentName;
    }

    /** Sets the value of the 'instrumentName' field */
    public Builder setInstrumentName(String value) {
      validate(fields()[3], value);
      this.instrumentName = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /** Checks whether the 'instrumentName' field has been set */
    public boolean hasInstrumentName() {
      return fieldSetFlags()[3];
    }

    /** Clears the value of the 'instrumentName' field */
    public Builder clearInstrumentName() {
      instrumentName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'instrumentDesignator' field */
    public InstrumentDesignator getInstrumentDesignator() {
      return instrumentDesignator;
    }

    /** Sets the value of the 'instrumentDesignator' field */
    public Builder setInstrumentDesignator(InstrumentDesignator value) {
      validate(fields()[4], value);
      this.instrumentDesignator = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /** Checks whether the 'instrumentDesignator' field has been set */
    public boolean hasInstrumentDesignator() {
      return fieldSetFlags()[4];
    }

    /** Clears the value of the 'instrumentDesignator' field */
    public Builder clearInstrumentDesignator() {
      instrumentDesignator = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'longMarginRate' field */
    public Double getLongMarginRate() {
      return longMarginRate;
    }

    /** Sets the value of the 'longMarginRate' field */
    public Builder setLongMarginRate(double value) {
      validate(fields()[5], value);
      this.longMarginRate = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /** Checks whether the 'longMarginRate' field has been set */
    public boolean hasLongMarginRate() {
      return fieldSetFlags()[5];
    }

    /** Clears the value of the 'longMarginRate' field */
    public Builder clearLongMarginRate() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'shortMarginRate' field */
    public Double getShortMarginRate() {
      return shortMarginRate;
    }

    /** Sets the value of the 'shortMarginRate' field */
    public Builder setShortMarginRate(double value) {
      validate(fields()[6], value);
      this.shortMarginRate = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /** Checks whether the 'shortMarginRate' field has been set */
    public boolean hasShortMarginRate() {
      return fieldSetFlags()[6];
    }

    /** Clears the value of the 'shortMarginRate' field */
    public Builder clearShortMarginRate() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'openComissionRate' field */
    public Double getOpenComissionRate() {
      return openComissionRate;
    }

    /** Sets the value of the 'openComissionRate' field */
    public Builder setOpenComissionRate(double value) {
      validate(fields()[7], value);
      this.openComissionRate = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /** Checks whether the 'openComissionRate' field has been set */
    public boolean hasOpenComissionRate() {
      return fieldSetFlags()[7];
    }

    /** Clears the value of the 'openComissionRate' field */
    public Builder clearOpenComissionRate() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'closeComissionRate' field */
    public Double getCloseComissionRate() {
      return closeComissionRate;
    }

    /** Sets the value of the 'closeComissionRate' field */
    public Builder setCloseComissionRate(double value) {
      validate(fields()[8], value);
      this.closeComissionRate = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /** Checks whether the 'closeComissionRate' field has been set */
    public boolean hasCloseComissionRate() {
      return fieldSetFlags()[8];
    }

    /** Clears the value of the 'closeComissionRate' field */
    public Builder clearCloseComissionRate() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'price' field */
    public Double getPrice() {
      return price;
    }

    /** Sets the value of the 'price' field */
    public Builder setPrice(double value) {
      validate(fields()[9], value);
      this.price = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /** Checks whether the 'price' field has been set */
    public boolean hasPrice() {
      return fieldSetFlags()[9];
    }

    /** Clears the value of the 'price' field */
    public Builder clearPrice() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'openPrice' field */
    public Double getOpenPrice() {
      return openPrice;
    }

    /** Sets the value of the 'openPrice' field */
    public Builder setOpenPrice(double value) {
      validate(fields()[10], value);
      this.openPrice = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /** Checks whether the 'openPrice' field has been set */
    public boolean hasOpenPrice() {
      return fieldSetFlags()[10];
    }

    /** Clears the value of the 'openPrice' field */
    public Builder clearOpenPrice() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'closePrice' field */
    public Double getClosePrice() {
      return closePrice;
    }

    /** Sets the value of the 'closePrice' field */
    public Builder setClosePrice(double value) {
      validate(fields()[11], value);
      this.closePrice = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /** Checks whether the 'closePrice' field has been set */
    public boolean hasClosePrice() {
      return fieldSetFlags()[11];
    }

    /** Clears the value of the 'closePrice' field */
    public Builder clearClosePrice() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'highPrice' field */
    public Double getHighPrice() {
      return highPrice;
    }

    /** Sets the value of the 'highPrice' field */
    public Builder setHighPrice(double value) {
      validate(fields()[12], value);
      this.highPrice = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /** Checks whether the 'highPrice' field has been set */
    public boolean hasHighPrice() {
      return fieldSetFlags()[12];
    }

    /** Clears the value of the 'highPrice' field */
    public Builder clearHighPrice() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'lowPrice' field */
    public Double getLowPrice() {
      return lowPrice;
    }

    /** Sets the value of the 'lowPrice' field */
    public Builder setLowPrice(double value) {
      validate(fields()[13], value);
      this.lowPrice = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /** Checks whether the 'lowPrice' field has been set */
    public boolean hasLowPrice() {
      return fieldSetFlags()[13];
    }

    /** Clears the value of the 'lowPrice' field */
    public Builder clearLowPrice() {
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'highLimit' field */
    public Double getHighLimit() {
      return highLimit;
    }

    /** Sets the value of the 'highLimit' field */
    public Builder setHighLimit(double value) {
      validate(fields()[14], value);
      this.highLimit = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /** Checks whether the 'highLimit' field has been set */
    public boolean hasHighLimit() {
      return fieldSetFlags()[14];
    }

    /** Clears the value of the 'highLimit' field */
    public Builder clearHighLimit() {
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'lowLimit' field */
    public Double getLowLimit() {
      return lowLimit;
    }

    /** Sets the value of the 'lowLimit' field */
    public Builder setLowLimit(double value) {
      validate(fields()[15], value);
      this.lowLimit = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /** Checks whether the 'lowLimit' field has been set */
    public boolean hasLowLimit() {
      return fieldSetFlags()[15];
    }

    /** Clears the value of the 'lowLimit' field */
    public Builder clearLowLimit() {
      fieldSetFlags()[15] = false;
      return this;
    }

    /** Gets the value of the 'volume' field */
    public Long getVolume() {
      return volume;
    }

    /** Sets the value of the 'volume' field */
    public Builder setVolume(long value) {
      validate(fields()[16], value);
      this.volume = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /** Checks whether the 'volume' field has been set */
    public boolean hasVolume() {
      return fieldSetFlags()[16];
    }

    /** Clears the value of the 'volume' field */
    public Builder clearVolume() {
      fieldSetFlags()[16] = false;
      return this;
    }

    /** Gets the value of the 'settlementPrice' field */
    public Double getSettlementPrice() {
      return settlementPrice;
    }

    /** Sets the value of the 'settlementPrice' field */
    public Builder setSettlementPrice(double value) {
      validate(fields()[17], value);
      this.settlementPrice = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /** Checks whether the 'settlementPrice' field has been set */
    public boolean hasSettlementPrice() {
      return fieldSetFlags()[17];
    }

    /** Clears the value of the 'settlementPrice' field */
    public Builder clearSettlementPrice() {
      fieldSetFlags()[17] = false;
      return this;
    }

    /** Gets the value of the 'bid' field */
    public Double getBid() {
      return bid;
    }

    /** Sets the value of the 'bid' field */
    public Builder setBid(double value) {
      validate(fields()[18], value);
      this.bid = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /** Checks whether the 'bid' field has been set */
    public boolean hasBid() {
      return fieldSetFlags()[18];
    }

    /** Clears the value of the 'bid' field */
    public Builder clearBid() {
      fieldSetFlags()[18] = false;
      return this;
    }

    /** Gets the value of the 'ask' field */
    public Double getAsk() {
      return ask;
    }

    /** Sets the value of the 'ask' field */
    public Builder setAsk(double value) {
      validate(fields()[19], value);
      this.ask = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /** Checks whether the 'ask' field has been set */
    public boolean hasAsk() {
      return fieldSetFlags()[19];
    }

    /** Clears the value of the 'ask' field */
    public Builder clearAsk() {
      fieldSetFlags()[19] = false;
      return this;
    }

    /** Gets the value of the 'unitSize' field */
    public Integer getUnitSize() {
      return unitSize;
    }

    /** Sets the value of the 'unitSize' field */
    public Builder setUnitSize(int value) {
      validate(fields()[20], value);
      this.unitSize = value;
      fieldSetFlags()[20] = true;
      return this;
    }

    /** Checks whether the 'unitSize' field has been set */
    public boolean hasUnitSize() {
      return fieldSetFlags()[20];
    }

    /** Clears the value of the 'unitSize' field */
    public Builder clearUnitSize() {
      fieldSetFlags()[20] = false;
      return this;
    }

    /** Gets the value of the 'createDate' field */
    public String getCreateDate() {
      return createDate;
    }

    /** Sets the value of the 'createDate' field */
    public Builder setCreateDate(String value) {
      validate(fields()[21], value);
      this.createDate = value;
      fieldSetFlags()[21] = true;
      return this;
    }

    /** Checks whether the 'createDate' field has been set */
    public boolean hasCreateDate() {
      return fieldSetFlags()[21];
    }

    /** Clears the value of the 'createDate' field */
    public Builder clearCreateDate() {
      createDate = null;
      fieldSetFlags()[21] = false;
      return this;
    }

    @Override
    public InstrumentMessage build() {
      try {
        InstrumentMessage record = new InstrumentMessage();
        record.exchangeID = fieldSetFlags()[0] ? this.exchangeID : (String) defaultValue(fields()[0]);
        record.exchangeName = fieldSetFlags()[1] ? this.exchangeName : (String) defaultValue(fields()[1]);
        record.instrumentID = fieldSetFlags()[2] ? this.instrumentID : (String) defaultValue(fields()[2]);
        record.instrumentName = fieldSetFlags()[3] ? this.instrumentName : (String) defaultValue(fields()[3]);
        record.instrumentDesignator = fieldSetFlags()[4] ? this.instrumentDesignator : (InstrumentDesignator) defaultValue(fields()[4]);
        record.longMarginRate = fieldSetFlags()[5] ? this.longMarginRate : (Double) defaultValue(fields()[5]);
        record.shortMarginRate = fieldSetFlags()[6] ? this.shortMarginRate : (Double) defaultValue(fields()[6]);
        record.openComissionRate = fieldSetFlags()[7] ? this.openComissionRate : (Double) defaultValue(fields()[7]);
        record.closeComissionRate = fieldSetFlags()[8] ? this.closeComissionRate : (Double) defaultValue(fields()[8]);
        record.price = fieldSetFlags()[9] ? this.price : (Double) defaultValue(fields()[9]);
        record.openPrice = fieldSetFlags()[10] ? this.openPrice : (Double) defaultValue(fields()[10]);
        record.closePrice = fieldSetFlags()[11] ? this.closePrice : (Double) defaultValue(fields()[11]);
        record.highPrice = fieldSetFlags()[12] ? this.highPrice : (Double) defaultValue(fields()[12]);
        record.lowPrice = fieldSetFlags()[13] ? this.lowPrice : (Double) defaultValue(fields()[13]);
        record.highLimit = fieldSetFlags()[14] ? this.highLimit : (Double) defaultValue(fields()[14]);
        record.lowLimit = fieldSetFlags()[15] ? this.lowLimit : (Double) defaultValue(fields()[15]);
        record.volume = fieldSetFlags()[16] ? this.volume : (Long) defaultValue(fields()[16]);
        record.settlementPrice = fieldSetFlags()[17] ? this.settlementPrice : (Double) defaultValue(fields()[17]);
        record.bid = fieldSetFlags()[18] ? this.bid : (Double) defaultValue(fields()[18]);
        record.ask = fieldSetFlags()[19] ? this.ask : (Double) defaultValue(fields()[19]);
        record.unitSize = fieldSetFlags()[20] ? this.unitSize : (Integer) defaultValue(fields()[20]);
        record.createDate = fieldSetFlags()[21] ? this.createDate : (String) defaultValue(fields()[21]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
