/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.aqitrade.raduga.messagebus.messages;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum InstrumentDesignator { 
  cash_instrument, future_instrument, stock_instrument  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"InstrumentDesignator\",\"namespace\":\"com.aqitrade.raduga.messagebus.messages\",\"symbols\":[\"cash_instrument\",\"future_instrument\",\"stock_instrument\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
