/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.aqitrade.raduga.messagebus.messages;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum OrderFlag { 
  order_flag_close_today  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OrderFlag\",\"namespace\":\"com.aqitrade.raduga.messagebus.messages\",\"symbols\":[\"order_flag_close_today\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
