/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.aqitrade.raduga.messagebus.messages;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum OrderDirection1 { 
  order_direction1_long, order_direction1_short  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OrderDirection1\",\"namespace\":\"com.aqitrade.raduga.messagebus.messages\",\"symbols\":[\"order_direction1_long\",\"order_direction1_short\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
