/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.aqitrade.raduga.messagebus.messages;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum PositionDesignator { 
  cash_position, future_position  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PositionDesignator\",\"namespace\":\"com.aqitrade.raduga.messagebus.messages\",\"symbols\":[\"cash_position\",\"future_position\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
