/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.aqitrade.raduga.messagebus.messages;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PositionMessagePosition extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PositionMessagePosition\",\"namespace\":\"com.aqitrade.raduga.messagebus.messages\",\"fields\":[{\"name\":\"designator\",\"type\":{\"type\":\"enum\",\"name\":\"PositionDesignator\",\"symbols\":[\"cash_position\",\"future_position\"]}},{\"name\":\"symbol\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"avgPrice\",\"type\":\"double\"},{\"name\":\"qty\",\"type\":\"double\"},{\"name\":\"direction\",\"type\":{\"type\":\"enum\",\"name\":\"PositionDirection\",\"symbols\":[\"position_direction_long\",\"position_direction_short\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public PositionDesignator designator;
  @Deprecated public String symbol;
  @Deprecated public double avgPrice;
  @Deprecated public double qty;
  @Deprecated public PositionDirection direction;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}.
   */
  public PositionMessagePosition() {}

  /**
   * All-args constructor.
   */
  public PositionMessagePosition(PositionDesignator designator, String symbol, Double avgPrice, Double qty, PositionDirection direction) {
    this.designator = designator;
    this.symbol = symbol;
    this.avgPrice = avgPrice;
    this.qty = qty;
    this.direction = direction;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return designator;
    case 1: return symbol;
    case 2: return avgPrice;
    case 3: return qty;
    case 4: return direction;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: designator = (PositionDesignator)value$; break;
    case 1: symbol = (String)value$; break;
    case 2: avgPrice = (Double)value$; break;
    case 3: qty = (Double)value$; break;
    case 4: direction = (PositionDirection)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'designator' field.
   */
  public PositionDesignator getDesignator() {
    return designator;
  }

  /**
   * Sets the value of the 'designator' field.
   * @param value the value to set.
   */
  public void setDesignator(PositionDesignator value) {
    this.designator = value;
  }

  /**
   * Gets the value of the 'symbol' field.
   */
  public String getSymbol() {
    return symbol;
  }

  /**
   * Sets the value of the 'symbol' field.
   * @param value the value to set.
   */
  public void setSymbol(String value) {
    this.symbol = value;
  }

  /**
   * Gets the value of the 'avgPrice' field.
   */
  public Double getAvgPrice() {
    return avgPrice;
  }

  /**
   * Sets the value of the 'avgPrice' field.
   * @param value the value to set.
   */
  public void setAvgPrice(Double value) {
    this.avgPrice = value;
  }

  /**
   * Gets the value of the 'qty' field.
   */
  public Double getQty() {
    return qty;
  }

  /**
   * Sets the value of the 'qty' field.
   * @param value the value to set.
   */
  public void setQty(Double value) {
    this.qty = value;
  }

  /**
   * Gets the value of the 'direction' field.
   */
  public PositionDirection getDirection() {
    return direction;
  }

  /**
   * Sets the value of the 'direction' field.
   * @param value the value to set.
   */
  public void setDirection(PositionDirection value) {
    this.direction = value;
  }

  /** Creates a new PositionMessagePosition RecordBuilder */
  public static Builder newBuilder() {
    return new Builder();
  }

  /** Creates a new PositionMessagePosition RecordBuilder by copying an existing Builder */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }

  /** Creates a new PositionMessagePosition RecordBuilder by copying an existing PositionMessagePosition instance */
  public static Builder newBuilder(PositionMessagePosition other) {
    return new Builder(other);
  }

  /**
   * RecordBuilder for PositionMessagePosition instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PositionMessagePosition>
    implements org.apache.avro.data.RecordBuilder<PositionMessagePosition> {

    private PositionDesignator designator;
    private String symbol;
    private double avgPrice;
    private double qty;
    private PositionDirection direction;

    /** Creates a new Builder */
    private Builder() {
      super(PositionMessagePosition.SCHEMA$);
    }

    /** Creates a Builder by copying an existing Builder */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.designator)) {
        this.designator = data().deepCopy(fields()[0].schema(), other.designator);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.symbol)) {
        this.symbol = data().deepCopy(fields()[1].schema(), other.symbol);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.avgPrice)) {
        this.avgPrice = data().deepCopy(fields()[2].schema(), other.avgPrice);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.qty)) {
        this.qty = data().deepCopy(fields()[3].schema(), other.qty);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.direction)) {
        this.direction = data().deepCopy(fields()[4].schema(), other.direction);
        fieldSetFlags()[4] = true;
      }
    }

    /** Creates a Builder by copying an existing PositionMessagePosition instance */
    private Builder(PositionMessagePosition other) {
            super(PositionMessagePosition.SCHEMA$);
      if (isValidValue(fields()[0], other.designator)) {
        this.designator = data().deepCopy(fields()[0].schema(), other.designator);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.symbol)) {
        this.symbol = data().deepCopy(fields()[1].schema(), other.symbol);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.avgPrice)) {
        this.avgPrice = data().deepCopy(fields()[2].schema(), other.avgPrice);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.qty)) {
        this.qty = data().deepCopy(fields()[3].schema(), other.qty);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.direction)) {
        this.direction = data().deepCopy(fields()[4].schema(), other.direction);
        fieldSetFlags()[4] = true;
      }
    }

    /** Gets the value of the 'designator' field */
    public PositionDesignator getDesignator() {
      return designator;
    }

    /** Sets the value of the 'designator' field */
    public Builder setDesignator(PositionDesignator value) {
      validate(fields()[0], value);
      this.designator = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /** Checks whether the 'designator' field has been set */
    public boolean hasDesignator() {
      return fieldSetFlags()[0];
    }

    /** Clears the value of the 'designator' field */
    public Builder clearDesignator() {
      designator = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'symbol' field */
    public String getSymbol() {
      return symbol;
    }

    /** Sets the value of the 'symbol' field */
    public Builder setSymbol(String value) {
      validate(fields()[1], value);
      this.symbol = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /** Checks whether the 'symbol' field has been set */
    public boolean hasSymbol() {
      return fieldSetFlags()[1];
    }

    /** Clears the value of the 'symbol' field */
    public Builder clearSymbol() {
      symbol = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'avgPrice' field */
    public Double getAvgPrice() {
      return avgPrice;
    }

    /** Sets the value of the 'avgPrice' field */
    public Builder setAvgPrice(double value) {
      validate(fields()[2], value);
      this.avgPrice = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /** Checks whether the 'avgPrice' field has been set */
    public boolean hasAvgPrice() {
      return fieldSetFlags()[2];
    }

    /** Clears the value of the 'avgPrice' field */
    public Builder clearAvgPrice() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'qty' field */
    public Double getQty() {
      return qty;
    }

    /** Sets the value of the 'qty' field */
    public Builder setQty(double value) {
      validate(fields()[3], value);
      this.qty = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /** Checks whether the 'qty' field has been set */
    public boolean hasQty() {
      return fieldSetFlags()[3];
    }

    /** Clears the value of the 'qty' field */
    public Builder clearQty() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'direction' field */
    public PositionDirection getDirection() {
      return direction;
    }

    /** Sets the value of the 'direction' field */
    public Builder setDirection(PositionDirection value) {
      validate(fields()[4], value);
      this.direction = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /** Checks whether the 'direction' field has been set */
    public boolean hasDirection() {
      return fieldSetFlags()[4];
    }

    /** Clears the value of the 'direction' field */
    public Builder clearDirection() {
      direction = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public PositionMessagePosition build() {
      try {
        PositionMessagePosition record = new PositionMessagePosition();
        record.designator = fieldSetFlags()[0] ? this.designator : (PositionDesignator) defaultValue(fields()[0]);
        record.symbol = fieldSetFlags()[1] ? this.symbol : (String) defaultValue(fields()[1]);
        record.avgPrice = fieldSetFlags()[2] ? this.avgPrice : (Double) defaultValue(fields()[2]);
        record.qty = fieldSetFlags()[3] ? this.qty : (Double) defaultValue(fields()[3]);
        record.direction = fieldSetFlags()[4] ? this.direction : (PositionDirection) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
