/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.aqitrade.raduga.messagebus.messages;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum PositionDirection { 
  position_direction_long, position_direction_short  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PositionDirection\",\"namespace\":\"com.aqitrade.raduga.messagebus.messages\",\"symbols\":[\"position_direction_long\",\"position_direction_short\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
