/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.aqitrade.raduga.messagebus.messages;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PositionMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PositionMessage\",\"namespace\":\"com.aqitrade.raduga.messagebus.messages\",\"fields\":[{\"name\":\"accountID\",\"type\":\"long\"},{\"name\":\"createDate\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"position\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"PositionMessagePosition\",\"fields\":[{\"name\":\"designator\",\"type\":{\"type\":\"enum\",\"name\":\"PositionDesignator\",\"symbols\":[\"cash_position\",\"future_position\"]}},{\"name\":\"symbol\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"avgPrice\",\"type\":\"double\"},{\"name\":\"qty\",\"type\":\"double\"},{\"name\":\"direction\",\"type\":{\"type\":\"enum\",\"name\":\"PositionDirection\",\"symbols\":[\"position_direction_long\",\"position_direction_short\"]}}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public long accountID;
  @Deprecated public String createDate;
  @Deprecated public java.util.List<PositionMessagePosition> position;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}.
   */
  public PositionMessage() {}

  /**
   * All-args constructor.
   */
  public PositionMessage(Long accountID, String createDate, java.util.List<PositionMessagePosition> position) {
    this.accountID = accountID;
    this.createDate = createDate;
    this.position = position;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return accountID;
    case 1: return createDate;
    case 2: return position;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: accountID = (Long)value$; break;
    case 1: createDate = (String)value$; break;
    case 2: position = (java.util.List<PositionMessagePosition>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'accountID' field.
   */
  public Long getAccountID() {
    return accountID;
  }

  /**
   * Sets the value of the 'accountID' field.
   * @param value the value to set.
   */
  public void setAccountID(Long value) {
    this.accountID = value;
  }

  /**
   * Gets the value of the 'createDate' field.
   */
  public String getCreateDate() {
    return createDate;
  }

  /**
   * Sets the value of the 'createDate' field.
   * @param value the value to set.
   */
  public void setCreateDate(String value) {
    this.createDate = value;
  }

  /**
   * Gets the value of the 'position' field.
   */
  public java.util.List<PositionMessagePosition> getPosition() {
    return position;
  }

  /**
   * Sets the value of the 'position' field.
   * @param value the value to set.
   */
  public void setPosition(java.util.List<PositionMessagePosition> value) {
    this.position = value;
  }

  /** Creates a new PositionMessage RecordBuilder */
  public static Builder newBuilder() {
    return new Builder();
  }

  /** Creates a new PositionMessage RecordBuilder by copying an existing Builder */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }

  /** Creates a new PositionMessage RecordBuilder by copying an existing PositionMessage instance */
  public static Builder newBuilder(PositionMessage other) {
    return new Builder(other);
  }

  /**
   * RecordBuilder for PositionMessage instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PositionMessage>
    implements org.apache.avro.data.RecordBuilder<PositionMessage> {

    private long accountID;
    private String createDate;
    private java.util.List<PositionMessagePosition> position;

    /** Creates a new Builder */
    private Builder() {
      super(PositionMessage.SCHEMA$);
    }

    /** Creates a Builder by copying an existing Builder */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.accountID)) {
        this.accountID = data().deepCopy(fields()[0].schema(), other.accountID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.createDate)) {
        this.createDate = data().deepCopy(fields()[1].schema(), other.createDate);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.position)) {
        this.position = data().deepCopy(fields()[2].schema(), other.position);
        fieldSetFlags()[2] = true;
      }
    }

    /** Creates a Builder by copying an existing PositionMessage instance */
    private Builder(PositionMessage other) {
            super(PositionMessage.SCHEMA$);
      if (isValidValue(fields()[0], other.accountID)) {
        this.accountID = data().deepCopy(fields()[0].schema(), other.accountID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.createDate)) {
        this.createDate = data().deepCopy(fields()[1].schema(), other.createDate);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.position)) {
        this.position = data().deepCopy(fields()[2].schema(), other.position);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'accountID' field */
    public Long getAccountID() {
      return accountID;
    }

    /** Sets the value of the 'accountID' field */
    public Builder setAccountID(long value) {
      validate(fields()[0], value);
      this.accountID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /** Checks whether the 'accountID' field has been set */
    public boolean hasAccountID() {
      return fieldSetFlags()[0];
    }

    /** Clears the value of the 'accountID' field */
    public Builder clearAccountID() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'createDate' field */
    public String getCreateDate() {
      return createDate;
    }

    /** Sets the value of the 'createDate' field */
    public Builder setCreateDate(String value) {
      validate(fields()[1], value);
      this.createDate = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /** Checks whether the 'createDate' field has been set */
    public boolean hasCreateDate() {
      return fieldSetFlags()[1];
    }

    /** Clears the value of the 'createDate' field */
    public Builder clearCreateDate() {
      createDate = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'position' field */
    public java.util.List<PositionMessagePosition> getPosition() {
      return position;
    }

    /** Sets the value of the 'position' field */
    public Builder setPosition(java.util.List<PositionMessagePosition> value) {
      validate(fields()[2], value);
      this.position = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /** Checks whether the 'position' field has been set */
    public boolean hasPosition() {
      return fieldSetFlags()[2];
    }

    /** Clears the value of the 'position' field */
    public Builder clearPosition() {
      position = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public PositionMessage build() {
      try {
        PositionMessage record = new PositionMessage();
        record.accountID = fieldSetFlags()[0] ? this.accountID : (Long) defaultValue(fields()[0]);
        record.createDate = fieldSetFlags()[1] ? this.createDate : (String) defaultValue(fields()[1]);
        record.position = fieldSetFlags()[2] ? this.position : (java.util.List<PositionMessagePosition>) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
