/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.aqitrade.raduga.messagebus.messages;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum TransactionDirection { 
  transaction_direction_long, transaction_direction_short  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TransactionDirection\",\"namespace\":\"com.aqitrade.raduga.messagebus.messages\",\"symbols\":[\"transaction_direction_long\",\"transaction_direction_short\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
