/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.aqitrade.raduga.messagebus.messages;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class UnsubscribeMarketDataMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UnsubscribeMarketDataMessage\",\"namespace\":\"com.aqitrade.raduga.messagebus.messages\",\"fields\":[{\"name\":\"instrumentID\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}},{\"name\":\"createDate\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.util.List<String> instrumentID;
  @Deprecated public String createDate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}.
   */
  public UnsubscribeMarketDataMessage() {}

  /**
   * All-args constructor.
   */
  public UnsubscribeMarketDataMessage(java.util.List<String> instrumentID, String createDate) {
    this.instrumentID = instrumentID;
    this.createDate = createDate;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return instrumentID;
    case 1: return createDate;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: instrumentID = (java.util.List<String>)value$; break;
    case 1: createDate = (String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'instrumentID' field.
   */
  public java.util.List<String> getInstrumentID() {
    return instrumentID;
  }

  /**
   * Sets the value of the 'instrumentID' field.
   * @param value the value to set.
   */
  public void setInstrumentID(java.util.List<String> value) {
    this.instrumentID = value;
  }

  /**
   * Gets the value of the 'createDate' field.
   */
  public String getCreateDate() {
    return createDate;
  }

  /**
   * Sets the value of the 'createDate' field.
   * @param value the value to set.
   */
  public void setCreateDate(String value) {
    this.createDate = value;
  }

  /** Creates a new UnsubscribeMarketDataMessage RecordBuilder */
  public static Builder newBuilder() {
    return new Builder();
  }

  /** Creates a new UnsubscribeMarketDataMessage RecordBuilder by copying an existing Builder */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }

  /** Creates a new UnsubscribeMarketDataMessage RecordBuilder by copying an existing UnsubscribeMarketDataMessage instance */
  public static Builder newBuilder(UnsubscribeMarketDataMessage other) {
    return new Builder(other);
  }

  /**
   * RecordBuilder for UnsubscribeMarketDataMessage instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UnsubscribeMarketDataMessage>
    implements org.apache.avro.data.RecordBuilder<UnsubscribeMarketDataMessage> {

    private java.util.List<String> instrumentID;
    private String createDate;

    /** Creates a new Builder */
    private Builder() {
      super(UnsubscribeMarketDataMessage.SCHEMA$);
    }

    /** Creates a Builder by copying an existing Builder */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.instrumentID)) {
        this.instrumentID = data().deepCopy(fields()[0].schema(), other.instrumentID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.createDate)) {
        this.createDate = data().deepCopy(fields()[1].schema(), other.createDate);
        fieldSetFlags()[1] = true;
      }
    }

    /** Creates a Builder by copying an existing UnsubscribeMarketDataMessage instance */
    private Builder(UnsubscribeMarketDataMessage other) {
            super(UnsubscribeMarketDataMessage.SCHEMA$);
      if (isValidValue(fields()[0], other.instrumentID)) {
        this.instrumentID = data().deepCopy(fields()[0].schema(), other.instrumentID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.createDate)) {
        this.createDate = data().deepCopy(fields()[1].schema(), other.createDate);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'instrumentID' field */
    public java.util.List<String> getInstrumentID() {
      return instrumentID;
    }

    /** Sets the value of the 'instrumentID' field */
    public Builder setInstrumentID(java.util.List<String> value) {
      validate(fields()[0], value);
      this.instrumentID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /** Checks whether the 'instrumentID' field has been set */
    public boolean hasInstrumentID() {
      return fieldSetFlags()[0];
    }

    /** Clears the value of the 'instrumentID' field */
    public Builder clearInstrumentID() {
      instrumentID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'createDate' field */
    public String getCreateDate() {
      return createDate;
    }

    /** Sets the value of the 'createDate' field */
    public Builder setCreateDate(String value) {
      validate(fields()[1], value);
      this.createDate = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /** Checks whether the 'createDate' field has been set */
    public boolean hasCreateDate() {
      return fieldSetFlags()[1];
    }

    /** Clears the value of the 'createDate' field */
    public Builder clearCreateDate() {
      createDate = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public UnsubscribeMarketDataMessage build() {
      try {
        UnsubscribeMarketDataMessage record = new UnsubscribeMarketDataMessage();
        record.instrumentID = fieldSetFlags()[0] ? this.instrumentID : (java.util.List<String>) defaultValue(fields()[0]);
        record.createDate = fieldSetFlags()[1] ? this.createDate : (String) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
